myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from myblog import views

from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.LoginView.as_view(), name='login'), 
    url(r'^post/', include('post.urls'))
]

post/urls.py
from django.conf.urls import url

from . import views


app_name = 'post'
urlpatterns = [
        url(r'^$', views.PostListView.as_view(), name="index"),
        url(r'^(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name="detail"),
        url(r'^create/$', views.PostCreateView.as_view(), name="create"),
        url(r'^update/(?P<pk>[0-9]+)/$', views.PostUpdateView.as_view(), name="update"),
        url(r'^delete/(?P<pk>[0-9]+)/$', views.PostDeleteView.as_view(), name="delete")
]

post/models.py
from django.db import models

from django.contrib.auth.models import User

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_subject = models.CharField(max_length=64)
    post_title = models.CharField(max_length=64)
    context = models.TextField()
    pub_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.post_title

class Comment(models.Model):
    author = models.ForeignKey(User)
    context = models.TextField()
    pub_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.author

myblog/forms.py
from django import forms

from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(label='ID', label_suffix='', max_length=64)
    password = forms.CharField(label='PASSWORD', label_suffix='', widget=forms.PasswordInput, max_length=64)

post/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post 

class PostCreateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)

    class Meta:
        model = Post
        fields = ['post_subject', 'post_title', 'context']
        labels = {
                'post_subject': '주제',
                'post_title': '제목',
                'context': '내용'
        }
        widgets = {'context': forms.HiddenInput()}

class PostUpdateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)

    class Meta:
        model = Post
        fields = ['post_subject', 'post_title', 'context']
        labels = {
                'post_subject': '주제',
                'post_title': '제목',
                'context': '내용'
        }
        widgets = {'context': forms.HiddenInput()}

myblog/views.py
from django.http import HttpResponseRedirect, JsonResponse

from django.contrib.auth import login, authenticate

from django.views import generic
from django.views.generic.edit import FormView
from django.core.urlresolvers import reverse_lazy
from .forms import LoginForm 

class LoginView(FormView):
    template_name = "login_form.html"
    form_class = LoginForm
    success_url = reverse_lazy('post:index')
    
    def form_valid(self, form):
        uid=form.cleaned_data['username']
        ups=form.cleaned_data['password']

        user = authenticate(username=uid, password=ups)
        if user is None:
            return JsonResponse({"asd": "adsd"})
        login(self.request, user)

        return super(LoginView, self).form_valid(form)
   

post/views.py
from django.views.generic import ListView, DetailView
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required

from post.models import Post, Comment
from post.forms import PostCreateForm, PostUpdateForm

@method_decorator(login_required, name='dispatch')
class PostListView(ListView):
    queryset = Post.objects.order_by('-pub_date')
    template_name = 'post/post_list.html'
    
@method_decorator(login_required, name='dispatch')
class PostDetailView(DetailView):
    model = Post
    template_name = 'post/post_detail.html'

@method_decorator(login_required, name='dispatch')
class PostCreateView(CreateView):
    model = Post
    form_class = PostCreateForm
    template_name = 'post/post_create_form.html'
    success_url = reverse_lazy('post:index')

    def form_valid(self, form):
        user = self.request.user
        form.instance.author = user
        return super(PostCreateView, self).form_valid(form)
    
@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
    model = Post
    form_class = PostUpdateForm
    template_name = 'post/post_update_form.html'
    success_url = reverse_lazy('post:index')

@method_decorator(login_required, name='dispatch')
class PostDeleteView(DeleteView):
    model = Post
    template_name = 'post/post_confirm_delete.html'
    success_url = reverse_lazy('post:index')

myblog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static "node_modules/normalize.css/normalize.css" %}">
        <link rel="stylesheet" href="{% static "bower_components/bootstrap/dist/css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "css/base.css" %}">
        <script type="text/javascript" src="{% static "bower_components/jquery/dist/jquery.min.js" %}"></script>
        <script type="text/javascirpt" src="{% static "bower_components/bootstrap/dist/js/bootstrap.min.js" %}"></script>
        <script type="text/javascript" src="{% static "bower_components/react/react-dom.min.js" %}"></script>
        <script type="text/javascript" src="{% static "bower_components/react/react-with-addons.min.js" %}"></script>
    </head>
    <body>
        <div class="container-fluid">
            <div class=row>
                {% block content %}
                {% endblock %}
            </div>
            {% block newrow %}
            {% endblock %}
        </div>
        {% block style %}
        {% endblock %}
        {% block js %}
        {% endblock %}
    </body>
</html>

myblog/templates/login_form.html
{% extends "base.html" %}
{% block title %}Login blog{% endblock %}
{% block content %}
<h1>Login</h1>
<div class="col-xs-4"></div>
<div class="col-xs-4" id="login">
    <form method="post">{% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Login" class="btn btn-success btn-sm">
    </form>
</div>
{% endblock %}
{% block style %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/login.css"%}">
{% endblock%}

post/templates/post/post_confirm_delete.html
{% extends "base.html" %}
{% block title %}Delete Post{% endblock %}
{% block content %}
<h1>Delete</h1>
<div class="col-xs-3"></div>
<div class="col-xs-6" id="delete">
    <form action="" method="post">{% csrf_token %}
        <strong>해당 게시물을 삭제하시겠습니까?<span style="color:red">"{{ object }}"</span></strong>
        <input type="submit" value="Confirm" class="btn btn-danger btn-xs"/>
    </form>
</div>
{% endblock %}
{% block style %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static "css/delete.css" %}" type="text/css" media="screen" title="no title" charset="utf-8">    
{% endblock %}

post/templates/post/post_create_form.html
{% extends "base.html" %}
{% block title %}Create Post{% endblock %}
{% block content %}
<h1>Write post</h1>
<div class="col-xs-2"></div>
<div class="col-xs-8" id="create">
    <form action="" method="post">{% csrf_token %}
        {{ form.as_table }}
        <label for="textarea">내용</label>
        <div id="textarea" contentEditable="true" role="textarea"></div>
        <input type="submit" value="Save" class="btn btn-success btn-xs"/>
    </form>
</div>
{% endblock %}
{% block style %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static "css/edit.css" %}" type="text/css" media="screen" title="no title" charset="utf-8">
{% endblock %}

{% block js%}
<script type="text/javascript" src="{% static "js/edit.js" %}"></script>    
{% endblock  %}

post/templates/post/post_detail.html
{% extends "base.html" %}
{% block title %}{{ object.post_title }}{% endblock %}
{% block content %}
<h1>{{ object.post_title }}</h1>
<div class="col-xs-2"></div>
<div class="col-xs-8" id="detail">
    <dl>
        <dt>주제 항목</dt>
        <dd>{{ object.post_subject }}</dt>
        <dt>내용</dt>
        <dd>{{ object.context }}</dt>
    </dl>
    <blockquote>
        <footer>작성자: {{ object.author }}, {{ object.pub_date }}</footer>
    </blockquote>
    <a href="{% url 'post:update' object.id %}" class="btn btn-default btn-xs active" role="button">Update</a>
    <a href="{% url 'post:delete' object.id %}" class="btn btn-default btn-xs active" role="button">Delete</a>
</div>
{% endblock %}
{% block style %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static "css/detail.css" %}" type="text/css" media="screen" title="no title" charset="utf-8">
<script type="text/javascript" charset="utf-8" src="{% static "js/detail.js" %}"></script>
{% endblock %}

post/templates/post/post_list.html
{% extends "base.html" %}
{% block title %}Post List{% endblock %}
{% block content %}
<h1>Post List</h1>
<div class="col-xs-2"></div>
<div class="col-xs-8" id="list">
    <table class="table-striped table-hover">
        <thead>
            <th>id</th>
            <th>subject</th>
            <th>title</th>
            <th>author</th>
            <th>date</th>
        <thead>
        <tbody>
        {% for post in object_list %}
            <tr>
                <td>{{ post.id }}</td>
                <td>{{ post.post_subject }}</td>
                <td><a href="{% url 'post:detail' post.id %}">{{ post.post_title }}</a></td>
                <td>{{ post.author }}</td>
                <td>{{ post.pub_date }}</td>
            </tr>
        {% empty %}
            <td colspan=5>포스트가 없습니다.</td>
        {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'post:create' %}" class="btn btn-primary btn-xs active" role="button">Create Post</a>
</div>
{% endblock %}
{% block style %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/list.css" %}">
{% endblock %}

post/templates/post/post_update_form.html
{% extends "base.html" %}
{% block title %}Update Post{% endblock %}
{% block content %}
<h1>Update</h1>
<div class="col-xs-2"></div>
<div class="col-xs-8" id="update">
    <form action="" method="post">{% csrf_token %}
        {{ form.as_table }}
        <label for="textarea">내용</label>
        <div id="textarea" contentEditable="true" role="textarea"></div>
        <input type="submit" value="Update" class="btn btn-success btn-xs"/>
    </form>
</div>
{% endblock %}
{% block style %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/edit.css" %}">
{% endblock %}
{% block js %}
<script type="text/javascript" src="{% static "js/edit.js" %}"></script>
{% endblock %}